<?php
/**
 * ContactTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * elasticemail_Restful_api
 *
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ContactTest Class Doc Comment
 *
 * @category    Class */
// * @description Contact
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ContactTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Contact"
     */
    public function testContact()
    {
    }

    /**
     * Test attribute "contact_score"
     */
    public function testPropertyContactScore()
    {
    }

    /**
     * Test attribute "date_added"
     */
    public function testPropertyDateAdded()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "bounced_error_code"
     */
    public function testPropertyBouncedErrorCode()
    {
    }

    /**
     * Test attribute "bounced_error_message"
     */
    public function testPropertyBouncedErrorMessage()
    {
    }

    /**
     * Test attribute "total_sent"
     */
    public function testPropertyTotalSent()
    {
    }

    /**
     * Test attribute "total_failed"
     */
    public function testPropertyTotalFailed()
    {
    }

    /**
     * Test attribute "total_opened"
     */
    public function testPropertyTotalOpened()
    {
    }

    /**
     * Test attribute "total_clicked"
     */
    public function testPropertyTotalClicked()
    {
    }

    /**
     * Test attribute "first_failed_date"
     */
    public function testPropertyFirstFailedDate()
    {
    }

    /**
     * Test attribute "last_failed_count"
     */
    public function testPropertyLastFailedCount()
    {
    }

    /**
     * Test attribute "date_updated"
     */
    public function testPropertyDateUpdated()
    {
    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {
    }

    /**
     * Test attribute "error_code"
     */
    public function testPropertyErrorCode()
    {
    }

    /**
     * Test attribute "friendly_error_message"
     */
    public function testPropertyFriendlyErrorMessage()
    {
    }

    /**
     * Test attribute "created_from_ip"
     */
    public function testPropertyCreatedFromIp()
    {
    }

    /**
     * Test attribute "consent_ip"
     */
    public function testPropertyConsentIp()
    {
    }

    /**
     * Test attribute "consent_date"
     */
    public function testPropertyConsentDate()
    {
    }

    /**
     * Test attribute "consent_tracking"
     */
    public function testPropertyConsentTracking()
    {
    }

    /**
     * Test attribute "unsubscribed_date"
     */
    public function testPropertyUnsubscribedDate()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "website_url"
     */
    public function testPropertyWebsiteUrl()
    {
    }

    /**
     * Test attribute "last_opened"
     */
    public function testPropertyLastOpened()
    {
    }

    /**
     * Test attribute "last_clicked"
     */
    public function testPropertyLastClicked()
    {
    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {
    }
}
