<?php
/**
 * EmailMergeMessageTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * elasticemail_Restful_api
 *
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EmailMergeMessageTest Class Doc Comment
 *
 * @category    Class */
// * @description EmailMergeMessage
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EmailMergeMessageTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EmailMergeMessage"
     */
    public function testEmailMergeMessage()
    {
    }

    /**
     * Test attribute "recipients"
     */
    public function testPropertyRecipients()
    {
    }

    /**
     * Test attribute "body"
     */
    public function testPropertyBody()
    {
    }

    /**
     * Test attribute "sender"
     */
    public function testPropertySender()
    {
    }

    /**
     * Test attribute "template_name"
     */
    public function testPropertyTemplateName()
    {
    }

    /**
     * Test attribute "attachments"
     */
    public function testPropertyAttachments()
    {
    }

    /**
     * Test attribute "tracking"
     */
    public function testPropertyTracking()
    {
    }

    /**
     * Test attribute "merge_fields"
     */
    public function testPropertyMergeFields()
    {
    }

    /**
     * Test attribute "headers"
     */
    public function testPropertyHeaders()
    {
    }

    /**
     * Test attribute "postback"
     */
    public function testPropertyPostback()
    {
    }

    /**
     * Test attribute "encoding"
     */
    public function testPropertyEncoding()
    {
    }

    /**
     * Test attribute "options"
     */
    public function testPropertyOptions()
    {
    }
}
