<?php
/**
 * RandomListPayloadTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * elasticemail_Restful_api
 *
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RandomListPayloadTest Class Doc Comment
 *
 * @category    Class */
// * @description RandomListPayload
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RandomListPayloadTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RandomListPayload"
     */
    public function testRandomListPayload()
    {
    }

    /**
     * Test attribute "list_name"
     */
    public function testPropertyListName()
    {
    }

    /**
     * Test attribute "count"
     */
    public function testPropertyCount()
    {
    }

    /**
     * Test attribute "exclude_blocked"
     */
    public function testPropertyExcludeBlocked()
    {
    }

    /**
     * Test attribute "allow_unsubscribe"
     */
    public function testPropertyAllowUnsubscribe()
    {
    }

    /**
     * Test attribute "rule"
     */
    public function testPropertyRule()
    {
    }

    /**
     * Test attribute "all_contacts"
     */
    public function testPropertyAllContacts()
    {
    }
}
