<?php
/**
 * SpamCheckTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * elasticemail_Restful_api
 *
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SpamCheckTest Class Doc Comment
 *
 * @category    Class */
// * @description Spam check of specified message.
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SpamCheckTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SpamCheck"
     */
    public function testSpamCheck()
    {
    }

    /**
     * Test attribute "total_score"
     */
    public function testPropertyTotalScore()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {
    }

    /**
     * Test attribute "from_email"
     */
    public function testPropertyFromEmail()
    {
    }

    /**
     * Test attribute "msg_id"
     */
    public function testPropertyMsgId()
    {
    }

    /**
     * Test attribute "channel_name"
     */
    public function testPropertyChannelName()
    {
    }

    /**
     * Test attribute "rules"
     */
    public function testPropertyRules()
    {
    }
}
