<?php
/**
 * SplitCampaignTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * elasticemail_Restful_api
 *
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SplitCampaignTest Class Doc Comment
 *
 * @category    Class */
// * @description SplitCampaign
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SplitCampaignTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SplitCampaign"
     */
    public function testSplitCampaign()
    {
    }

    /**
     * Test attribute "split_campaign_templates"
     */
    public function testPropertySplitCampaignTemplates()
    {
    }

    /**
     * Test attribute "trigger_options"
     */
    public function testPropertyTriggerOptions()
    {
    }

    /**
     * Test attribute "split_options"
     */
    public function testPropertySplitOptions()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "targets"
     */
    public function testPropertyTargets()
    {
    }

    /**
     * Test attribute "tracking_options"
     */
    public function testPropertyTrackingOptions()
    {
    }

    /**
     * Test attribute "options"
     */
    public function testPropertyOptions()
    {
    }
}
