<?php
/**
 * WebhookTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * elasticemail_Restful_api
 *
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * WebhookTest Class Doc Comment
 *
 * @category    Class */
// * @description Notification webhook setting
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WebhookTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Webhook"
     */
    public function testWebhook()
    {
    }

    /**
     * Test attribute "webhook_id"
     */
    public function testPropertyWebhookId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "date_created"
     */
    public function testPropertyDateCreated()
    {
    }

    /**
     * Test attribute "date_updated"
     */
    public function testPropertyDateUpdated()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "notify_once_per_email"
     */
    public function testPropertyNotifyOncePerEmail()
    {
    }

    /**
     * Test attribute "notification_for_sent"
     */
    public function testPropertyNotificationForSent()
    {
    }

    /**
     * Test attribute "notification_for_opened"
     */
    public function testPropertyNotificationForOpened()
    {
    }

    /**
     * Test attribute "notification_for_clicked"
     */
    public function testPropertyNotificationForClicked()
    {
    }

    /**
     * Test attribute "notification_for_unsubscribed"
     */
    public function testPropertyNotificationForUnsubscribed()
    {
    }

    /**
     * Test attribute "notification_for_abuse_report"
     */
    public function testPropertyNotificationForAbuseReport()
    {
    }

    /**
     * Test attribute "notification_for_error"
     */
    public function testPropertyNotificationForError()
    {
    }
}
