<?php
/**
 * EmailsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * elasticemail_Restful_api
 *
 * Send your emails with ElasticEmail API
 *
 * OpenAPI spec version: 3.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * EmailsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EmailsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for emailsMergePost
     *
     * Send bulk merge email.
     *
     */
    public function testEmailsMergePost()
    {
    }

    /**
     * Test case for emailsMsgidViewGet
     *
     * View email.
     *
     */
    public function testEmailsMsgidViewGet()
    {
    }

    /**
     * Test case for emailsTransactionalPost
     *
     * Send transactional message (recipients will be known to each other).
     *
     */
    public function testEmailsTransactionalPost()
    {
    }

    /**
     * Test case for emailsTransactionidCancelPost
     *
     * Cancels emails that are waiting to be sent..
     *
     */
    public function testEmailsTransactionidCancelPost()
    {
    }

    /**
     * Test case for emailsTransactionidStatusGet
     *
     * Get email batch status.
     *
     */
    public function testEmailsTransactionidStatusGet()
    {
    }
}
